from django.urls import re_path



# import all above in one line not commented
from .views import (
    ProductItemList, ProductDetailList, AddNewProduct, AddProductItems,
    PurchasedItems, ExtraItemsView, ClaimedProductFormView, deletemark,
    ClaimedItemsListView, StockItemList, AddStockItems, StockOutItems,
    StockDetailView, StockInListView, StockOutListView, ProductUpdateView, validcommande,
    StockInUpdateView, addbulk, product_search, deleteproduct, lowstock, addoneproduct, getproducts, productslistbycategory, categories, addbulkcategory, deletecategory, addcategory, getproductsbycategory, searchproductsincategory, updateproduct, addstock, producthistory, supply, addsupply, reportnetprofit, reports, productsranking, downranking, relve, statsofrelve, addsupplier, dailystats, dailyproductsranking, dailyproductsrankingdown, bonentree, supplierslist, supplierinfo, addpaymentsupplier, addclient, dailystatsstock, bonsentrees, getlowbycategory, commandproduct, checkrefsaisi, checkrefupdate, updatecategory, productscommande, updatestock, updatecommande, marks, addmark, getsupplierproducts, cancelcommande, editsupp, retour, lowintwins, getlowintwins, updatebonline, searchrefinlow, filtercommandesupp, refexeption, refreshmark, searchrefinstock, refreshitemssupplier, lowinarr, getlowinarr, addproduct, duplicate, urgent, makeurgent, geturgentbycategory, minimumstock, getminbycategory, deleteproduct, updatemark, avoirsupp, cancelcommandesupp, deleteavoir, addreforigin, removereforigin, searchglobal, cancelcommanded, searchproduct, createbon, factureview, createfacture, deviseview, createdevise, listfacturespaye, listdevises, facturedetails, devisedetails, facturedetails1, facturedetails2, facturedetails3, addfactureitem, loadpdctsinstock, panier, generate_barcode, sorticontoir, sortiecomptoir, printbarcodes, barcodescan
)
from . import views
from pis_product.logs_view import DailyStockLogs, MonthlyStockLogs


urlpatterns = [
    #re_path(r'^getfacturedate/',views.getfacturedate, name='getfacturedate'),
    #re_path(r'^getfacturedate/',views.getfacturedate, name='getfacturedate'),
    re_path(r'^searchcomptaresult/',views.searchcomptaresult, name='searchcomptaresult'),
    re_path(r'^searchcompta/',views.searchcompta, name='searchcompta'),
    re_path(r'^listfacturesnonpaye/',views.listfacturesnonpaye, name='listfacturesnonpaye'),
    re_path(r'^listfacturesmanual/',views.listfacturesmanual, name='listfacturesmanual'),
    re_path(r'^reglerelve/',views.reglerelve, name='reglerelve'),
    re_path(r'^searchfacture/',views.searchfacture, name='searchfacture'),
    re_path(r'^getfacturedate/',views.getfacturedate, name='getfacturedate'),
    re_path(r'^printeffet/',views.printeffet, name='printeffet'),
    re_path(r'^zz/',views.zz, name='zz'),
    re_path(r'^updateclientphone/',views.updateclientphone, name='updateclientphone'),
    re_path(r'^pp/',views.pp, name='pp'),
    re_path(r'^reglefacture/',views.reglefacture, name='reglefacture'),
    re_path(r'^removefromcart/',views.removefromcart, name='removefromcart'),
    re_path(r'^deletedevi/',views.deletedevi, name='deletedevi'),
    re_path(r'^updatedevi/',views.updatedevi, name='updatedevi'),
    re_path(r'^modifierdevi/',views.modifierdevi, name='modifierdevi'),
    re_path(r'^addpdct/',views.addpdct, name='addpdct'),
    re_path(r'^updatereleve/',views.updatereleve, name='updatereleve'),
    re_path(r'^modifierreleve/',views.modifierreleve, name='modifierreleve'),
    re_path(r'^releveprint/',views.releveprint, name='releveprint'),
    re_path(r'^createreleve/',views.createreleve, name='createreleve'),
    re_path(r'^listreleve/',views.listreleve, name='listreleve'),
    re_path(r'^relveview/',views.relveview, name='relveview'),
    re_path(r'^updatefacture/',views.updatefacture, name='updatefacture'),
    re_path(r'^updateclientname/',views.updateclientname, name='updateclientname'),
    re_path(r'^modifierfacture/',views.modifierfacture, name='modifierfacture'),
    re_path(r'^updateclientice',views.updateclientice, name='updateclientice'),
    re_path(r'^deleteinfacture/',views.deleteinfacture, name='deleteinfacture'),
    re_path(r'^updatestockcontoir/',views.updatestockcontoir, name='updatestockcontoir'),
    re_path(r'^assignbarcode/',views.assignbarcode, name='assignbarcode'),
    re_path(r'^scanproductdata/',views.scanproductdata, name='scanproductdata'),
    re_path(r'^barcodescan/',barcodescan, name='barcodescan'),
    re_path(r'^printbarcodes/',printbarcodes, name='printbarcodes'),
    re_path(r'^sortiecomptoir/',sortiecomptoir, name='sortiecomptoir'),
    re_path(r'^sorticontoir',sorticontoir, name='sorticontoir'),
    re_path('generate-barcode/(?P<code>\d+)', generate_barcode, name='generate_barcode'),
    re_path(r'^panier',panier, name='panier'),
    re_path(r'^loadpdctsinstock/',loadpdctsinstock, name='loadpdctsinstock'),
    re_path(r'^devisedetails/(?P<id>\d+)',devisedetails, name='devisedetails'),
    re_path(r'^facturedetails/(?P<id>\d+)',facturedetails, name='facturedetails'),
    re_path(r'^facturedetails1/(?P<id>\d+)',facturedetails1, name='facturedetails1'),
    re_path(r'^facturedetails2/(?P<id>\d+)',facturedetails2, name='facturedetails2'),
    re_path(r'^facturedetails3/(?P<id>\d+)',facturedetails3, name='facturedetails3'),
    re_path(r'^addfactureitem',addfactureitem, name='addfactureitem'),
    re_path(r'^listdevises',listdevises, name='listdevises'),
    re_path(r'^listfacturespaye',listfacturespaye, name='listfacturespaye'),
    re_path(r'^createdevise',createdevise, name='createdevise'),
    re_path(r'^deviseview',deviseview, name='deviseview'),
    re_path(r'^createfacture',createfacture, name='createfacture'),
    re_path(r'^factureview',factureview, name='factureview'),
    re_path(r'^createbon',createbon, name='createbon'),
    re_path(r'^searchproduct',searchproduct, name='searchproduct'),
    re_path(r'^cancelcommanded',cancelcommanded, name='cancelcommanded'),
    re_path(r'^searchglobal',searchglobal, name='searchglobal'),
    re_path(r'^removereforigin',removereforigin, name='removereforigin'),
    re_path(r'^addreforigin',addreforigin, name='addreforigin'),
    re_path(r'^deleteavoir',deleteavoir, name='deleteavoir'),
    re_path(r'^cancelcommandesupp',cancelcommandesupp, name='cancelcommandesupp'),
    re_path(r'^geturgentbycategory',geturgentbycategory, name='geturgentbycategory'),
    re_path(r'^avoirsupp',avoirsupp, name='avoirsupp'),
    re_path(r'^updatemark',updatemark, name='updatemark'),
    re_path(r'^makeurgent',makeurgent, name='makeurgent'),
    re_path(r'^urgent/',urgent, name='urgent'),
    re_path(r'^duplicate/',duplicate, name='duplicate'),
    re_path(r'^addproduct/',addproduct, name='addproduct'),
    re_path(r'^getlowinarr/',getlowinarr, name='getlowinarr'),
    re_path(r'^lowinarr/',lowinarr, name='lowinarr'),
    re_path(r'^searchrefinstock/',searchrefinstock, name='searchrefinstock'),
    re_path(r'^refreshitemssupplier/',refreshitemssupplier, name='refreshitemssupplier'),
    re_path(r'^refreshmark/',refreshmark, name='refreshmark'),
    re_path(r'^refexeption/',refexeption, name='refexeption'),
    re_path(r'^filtercommandesupp/',filtercommandesupp, name='filtercommandesupp'),
    re_path(r'^validcommande/',validcommande, name='validcommande'),
    re_path(r'^searchrefinlow/',searchrefinlow, name='searchrefinlow'),
    re_path(r'^addclient/',addclient, name='addclient'),
    re_path(r'^deletemark/',deletemark, name='deletemark'),
    re_path(r'^updatebonline/(?P<id>\d+)',updatebonline, name='updatebonline'),
    re_path(r'^lowintwins/',lowintwins, name='lowintwins'),
    re_path(r'^getlowintwins/',getlowintwins, name='getlowintwins'),
    re_path(r'^retour/',retour, name='retour'),
    re_path(r'^marks/',marks, name='marks'),
    re_path(r'^editsupp/',editsupp, name='editsupp'),
    re_path(r'^getsupplierproducts/',getsupplierproducts, name='getsupplierproducts'),
    re_path(r'^addmark/',addmark, name='addmark'),
    re_path(r'^cancelcommande/',cancelcommande, name='cancelcommande'),
    re_path(r'^bonsentrees/',bonsentrees, name='bonsentrees'),
    re_path(r'^dailystatsstock/',dailystatsstock, name='dailystatsstock'),
    re_path(r'^bonentree/(?P<id>\d+)',bonentree, name='bonentree'),
    re_path(r'^supplierslist/',supplierslist, name='supplierslist'),
    re_path(r'^supplierinfo/(?P<id>\d+)',supplierinfo, name='supplierinfo'),
    re_path(r'^addpaymentsupplier/(?P<id>\d+)',addpaymentsupplier, name='addpaymentsupplier'),
    re_path(r'^dailystats/',dailystats, name='dailystats'),
    re_path(r'^checkrefsaisi/',checkrefsaisi, name='checkrefsaisi'),
    re_path(r'^checkrefupdate/',checkrefupdate, name='checkrefupdate'),
    re_path(r'^dailyproductsranking/',dailyproductsranking, name='dailyproductsranking'),
    re_path(r'^dailyproductsrankingdown/',dailyproductsrankingdown, name='dailyproductsrankingdown'),

    re_path(r'^items/list/$', ProductItemList.as_view(), name='items_list'),
    re_path(r'^items/addbulk/',addbulk, name='addbulk'),
    re_path(r'^product_search',product_search, name='product_search'),
    re_path(r'^item/(?P<pk>\d+)/detail/list/$',ProductDetailList.as_view(),name='item_details'),
    re_path(r'^item/(?P<product_id>\d+)/add/$',AddProductItems.as_view(),name='add_product_items'),
    re_path(r'^items/purchased/$', PurchasedItems.as_view(),name='purchased_items'),
    re_path(r'^items/extra/purchased/$', ExtraItemsView.as_view(),name='purchased_extra_items'),
    re_path(r'^items/claimed/$', ClaimedProductFormView.as_view(),name='claimed_items'),
    re_path(r'^items/claimed/list/$', ClaimedItemsListView.as_view(),name='claimed_items_list'),
    re_path(r'^retailer/(?P<retailer_id>\d+)/add/$',AddNewProduct.as_view(),name='add_product'),
    re_path(r'^stock/items/list/$', StockItemList.as_view(), name='stock_items_list'),
    re_path(r'^stock/item/(?P<product_id>\d+)/add/$',AddStockItems.as_view(),name='add_stock_items'),
    re_path(r'^stock/item/(?P<product_id>\d+)/out/$',StockOutItems.as_view(),name='stock_out_items'),
    re_path(r'^stock/item/(?P<product_id>\d+)/detail/$',StockDetailView.as_view(),name='stock_detail'),
    re_path(r'^(?P<product_id>\d+)/stock/in/$',StockInListView.as_view(),name='stockin_list'),
    re_path(r'^(?P<product_id>\d+)/stock/out/$',StockOutListView.as_view(),name='stockout_list'),
    re_path(r'^(?P<pk>\d+)/update/$',ProductUpdateView.as_view(),name='update_product'),
    re_path(r'^(?P<pk>\d+)/stockin/update/$',StockInUpdateView.as_view(),name='update_stockin'),
    re_path(r'^items/deleteproduct/',deleteproduct, name='delete_product'),
    re_path(r'^items/lowstock/',lowstock, name='lowstock'),
    re_path(r'^items/productscommande/',productscommande, name='productscommande'),
    re_path(r'^items/addoneproduct/',addoneproduct, name='addoneproduct'),
    re_path(r'^items/getproducts/',getproducts, name='getproducts'),
    re_path(r'^items/productslistbycategory/',productslistbycategory, name='productslistbycategory'),
    re_path(r'^items/categories/',categories, name='categories'),
    re_path(r'^items/addcategory/',addcategory, name='addcategory'),
    re_path(r'^items/getproductsbycategory/',getproductsbycategory, name='getproductsbycategory'),
    re_path(r'^items/getlowbycategory/',getlowbycategory, name='getlowbycategory'),
    re_path(r'^items/searchproductsincategory/',searchproductsincategory, name='searchproductsincategory'),
    re_path(r'^items/addbulkcategory/(?P<id>\d+)',addbulkcategory, name='addbulkcategory'),
    re_path(r'^updateproduct/(?P<id>\d+)',updateproduct, name='updateproduct'),
    re_path(r'^updatecategory/(?P<id>\d+)',updatecategory, name='updatecategory'),
    re_path(r'^producthistory/(?P<id>\d+)',producthistory, name='producthistory'),
    re_path(r'^updatestock/',updatestock, name='updatestock'),
    re_path(r'^items/commandproduct/',commandproduct, name='commandproduct'),
    re_path(r'^addstock/(?P<id>\d+)',addstock, name='addstock'),
    re_path(r'^items/deletecategory/(?P<id>\d+)',deletecategory, name='deletecategory'),
    re_path(r'^supply/',supply, name='supply'),
    re_path(r'^addsupply/',addsupply, name='addsupply'),
    re_path(r'^reports/',reports, name='reports'),
    re_path(r'^reportnetprofit/',reportnetprofit, name='reportnetprofit'),
    re_path(r'^relve/',relve, name='relve'),
    re_path(r'^statsofrelve/',statsofrelve, name='statsofrelve'),
    re_path(r'^productsranking/',productsranking, name='productsranking'),
    re_path(r'^downranking/',downranking, name='downranking'),
    re_path(r'^addsupplier/',addsupplier, name='addsupplier'),
    re_path(r'^updatecommande/',updatecommande, name='updatecommande'),
    re_path(r'^minimumstock/',minimumstock, name='minimumstock'),
    re_path(r'^getminbycategory/',getminbycategory, name='getminbycategory'),
    re_path(r'^deleteproduct/',deleteproduct, name='deleteproduct'),
    

    # Logs
    re_path(r'^stock/logs/daily/$', DailyStockLogs.as_view(),name='daily_stock_logs'),
    re_path(r'^stock/logs/monthly/$', MonthlyStockLogs.as_view(),name='monthly_stock_logs'),
]
